//
//  APIData.swift
//  WeatherApp
//
//  Created by User on 27.06.2023.
//

import Foundation

class APIData {
    let currentWeatherURL = "https://api.openweathermap.org/data/2.5/weather"
    let fiveDaysWeatherURL = "https://api.openweathermap.org/data/2.5/forecast"
    let geocodingURL = "https://api.openweathermap.org/geo/1.0/direct"
    
    let apiKey = "13a33900751abf85e9233aa3540caab8"
    
    let iconURL = "https://openweathermap.org/img/w/10d.png"
    
    static let directoryOfCities = [
        "Абакан": "Abakan",
        "Альметьевск": "Almetyevsk",
        "Анадырь": "Anadyr",
        "Анапа": "Anapa",
        "Архангельск": "Arkhangelsk",
        "Астрахань": "Astrakhan",
        "Барнаул": "Barnaul",
        "Белгород": "Belgorod",
        "Беслан": "Beslan",
        "Бийск": "Biysk",
        "Биробиджан": "Birobidzhan",
        "Благовещенск": "Blagoveshchensk",
        "Бологое": "Bologoye",
        "Брянск": "Bryansk",
        "Великий Новгород": "Veliky Novgorod",
        "Великий Устюг": "Veliky Ustyug",
        "Владивосток": "Vladivostok",
        "Владикавказ": "Vladikavkaz",
        "Владимир": "Vladimir",
        "Волгоград": "Volgograd",
        "Вологда": "Vologda",
        "Воркута": "Vorkuta",
        "Воронеж": "Voronezh",
        "Гатчина": "Gatchina",
        "Гдов": "Gdov",
        "Геленджик": "Gelendzhik",
        "Горно-Алтайск": "Gorno-Altaysk",
        "Грозный": "Grozny",
        "Гудермес": "Gudermes",
        "Гусь-Хрустальный": "Gus-Khrustalny",
        "Дзержинск": "Dzerzhinsk",
        "Дмитров": "Dmitrov",
        "Дубна": "Dubna",
        "Ейск": "Yeysk",
        "Екатеринбург": "Yekaterinburg",
        "Елабуга": "Yelabuga",
        "Елец": "Yelets",
        "Ессентуки": "Yessentuki",
        "Златоуст": "Zlatoust",
        "Иваново": "Ivanovo",
        "Ижевск": "Izhevsk",
        "Иркутск": "Irkutsk",
        "Йошкар-Ола": "Yoshkar-Ola",
        "Казань": "Kazan",
        "Калининград": "Kaliningrad",
        "Калуга": "Kaluga",
        "Кемерово": "Kemerovo",
        "Кисловодск": "Kislovodsk",
        "Комсомольск-на-Амуре": "Komsomolsk-on-Amur",
        "Котлас": "Kotlas",
        "Краснодар": "Krasnodar",
        "Красноярск": "Krasnoyarsk",
        "Курган": "Kurgan",
        "Курск": "Kursk",
        "Кызыл": "Kyzyl",
        "Лениногорск": "Leninogorsk",
        "Ленск": "Lensk",
        "Липецк": "Lipetsk",
        "Луга": "Luga",
        "Любань": "Lyuban",
        "Люберцы": "Lyubertsy",
        "Магадан": "Magadan",
        "Майкоп": "Maykop",
        "Махачкала": "Makhachkala",
        "Миасс": "Miass",
        "Минеральные Воды": "Mineralnye Vody",
        "Мирный": "Mirny",
        "Москва": "Moscow",
        "Мурманск": "Murmansk",
        "Муром": "Murom",
        "Мытищи": "Mytishchi",
        "Набережные Челны": "Naberezhnye Chelny",
        "Надым": "Nadym",
        "Нальчик": "Nalchik",
        "Назрань": "Nazran",
        "Нарьян-Мар": "Naryan-Mar",
        "Находка": "Nakhodka",
        "Нижневартовск": "Nizhnevartovsk",
        "Нижнекамск": "Nizhnekamsk",
        "Нижний Новгород": "Nizhny Novgorod",
        "Нижний Тагил": "Nizhny Tagil",
        "Новокузнецк": "Novokuznetsk",
        "Новосибирск": "Novosibirsk",
        "Новый Уренгой": "Novy Urengoy",
        "Норильск": "Norilsk",
        "Обнинск": "Obninsk",
        "Октябрьский": "Oktyabrsky",
        "Омск": "Omsk",
        "Оренбург": "Orenburg",
        "Орехово-Зуево": "Orekhovo-Zuyevo",
        "Орёл": "Oryol",
        "Пенза": "Penza",
        "Пермь": "Perm",
        "Петрозаводск": "Petrozavodsk",
        "Петропавловск-Камчатский": "Petropavlovsk-Kamchatsky",
        "Подольск": "Podolsk",
        "Псков": "Pskov",
        "Пятигорск": "Pyatigorsk",
        "Ростов-на-Дону": "Rostov-on-Don",
        "Рыбинск": "Rybinsk",
        "Рязань": "Ryazan",
        "Салехард": "Salekhard",
        "Самара": "Samara",
        "Санкт-Петербург": "Saint Petersburg",
        "Саранск": "Saransk",
        "Саратов": "Saratov",
        "Северодвинск": "Severodvinsk",
        "Смоленск": "Smolensk",
        "Соль-Илецк": "Sol-Iletsk",
        "Сочи": "Sochi",
        "Ставрополь": "Stavropol",
        "Стерлитамак": "Sterlitamak",
        "Сургут": "Surgut",
        "Сыктывкар": "Syktyvkar",
        "Тамбов": "Tambov",
        "Тверь": "Tver",
        "Тобольск": "Tobolsk",
        "Тольятти": "Tolyatti",
        "Томск": "Tomsk",
        "Туапсе": "Tuapse",
        "Тула": "Tula",
        "Тында": "Tynda",
        "Тюмень": "Tyumen",
        "Улан-Уде": "Ulan-Ude",
        "Ульяновск": "Ulyanovsk",
        "Уфа": "Ufa",
        "Хабаровск": "Khabarovsk",
        "Ханты-Мансийск": "Khanty-Mansiysk",
        "Чебаркуль": "Chebarkul",
        "Чебоксары": "Cheboksary",
        "Челябинск": "Chelyabinsk",
        "Череповец": "Cherepovets",
        "Черкесск": "Cherkessk",
        "Чистополь": "Chistopol",
        "Чита": "Chita",
        "Шадринск": "Shadrinsk",
        "Шатура": "Shatura",
        "Шуя": "Shuya",
        "Элиста": "Elista",
        "Энгельс": "Engels",
        "Южно-Сахалинск": "Yuzhno-Sakhalinsk",
        "Якутск": "Yakutsk",
        "Ярославль": "Yaroslavl"
    ]
}
